
name: TAGS - Build, Test and create a Release

on:
  push:
    tags:
        - 'v*' # push events matching to tag v* - ie. v1.0, v20.1.5

jobs:
  build:
    name: Build, Test and Create a Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 10.13
      uses: actions/setup-node@v1
      with:
         node-version: 10.13
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    
    - name: Create release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Release ${{ github.ref }}
        draft: false
        prerelease: ${{ contains( github.ref, 'beta' ) }}
